### ISSUE TITLE
The client must be able to periodically send status message to the Web-service

### ISSUE THREAD

**Issue by AxialDark** [P7-Team/P7-Client#61]
Tasks:
- [x] Define statuses that can be sent
- [ ] Implement HeartbeatClient which sends the request. Delegate response to relevant component, such as TaskClient if the response is a Task.

**Comment by MikaelVM** [comment]
Status types are: (Working, Available, Done, IsJobDone)
IsJobDone may have its name changed to something better, it represent the requester pinging the web service, asking whether its batch is done.

**Comment by AxialDark** [comment]
This is done, closing task
