### ISSUE TITLE
The Provider-client should be able to send the result of a Task to the Web-service

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Client#63]
Tasks:
- [x] Send result of Task  to the web-service in such a way that it conforms to the API specification. 
- [x] Serializes Result to JSON 
- [x] Expose an interface that allows other parts of the Client-Provider to pass a result to the web-service.
- [x] Implemented in TaskClient

**Comment by AxialDark** [comment]
Pull request is merged, closing task
